[package]
name = "fibe"
version = "0.0.1"
license = "Apache-2.0"
keywords = ["gamedev"]
authors = [
"Dzmitry Malyshau <kvarkus@gmail.com>",
]

[lib]
name = "fibe"

[dependencies]
log = "*"

[dependencies.pulse]
git = "https://github.com/csherratt/pulse.git"