[package]
name = "fibe"
version = "0.1.0"
license = "Apache-2.0"
keywords = ["gamedev"]
authors = ["Fibe-rs Hackers"]

[lib]
name = "fibe"

[dependencies]
log = "*"
atom = "*"
deque = "*"
rand = "*"
num_cpus = "*"

[dependencies.pulse]
git = "https://github.com/csherratt/pulse.git"
features = ["callback"]

[dev-dependencies]
timebomb = "*"